
server:
  port: 8079

spring:

  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/api/v1/clients/**
        - id: notification
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/api/v1/notifications/**
  datasource:
    url: jdbc:mysql://localhost:3366/gateway
    username: root
    password: root
    driver-classname: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: localhost

    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true