
server:
  port: 8086
spring:


  datasource:
    url: jdbc:mysql://localhost:3366/amqp
    username: root
    password: root
    driver-classname: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: amqp

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
